### ISSUE TITLE
old Arduino fashion 5 volt supply and TTL module

### ISSUE THREAD

**Issue by mkeyno** [chaeplin/PietteTech_DHT-8266#26]
hi @chaeplin , and thanks for intelligent  library , however I have general question for the module used to be for old Arduino fashion 5 volt supply and TTL , I know I should divide the analogue sensor voltage  to 1 volt for ESP ADC , but  what is your suggestion when we have digital device with 5 volt supply , how about the I2c output device? what is your best solution to convert those module to ESP-ready use module

BR

**Comment by chaeplin** [comment]
voltage devider is simple one. for i2c something like this https://www.adafruit.com/product/757
check ebay :)

**Comment by mkeyno** [comment]
why I2c module can't be set base on supply TTL voltage

**Comment by chaeplin** [comment]
interface of i2c(scl and sda) is pull-uped using supply voltage.

**Comment by mkeyno** [comment]
what's your mean ? you mean if supply the I2c device with any supply voltage , the SCI-SDA follow the same TTL?

**Comment by chaeplin** [comment]
check https://learn.sparkfun.com/tutorials/i2c (pull-up and signal level explained)

**Comment by mkeyno** [comment]
thanks for the link , regard to note I think wont be problem to supply old Arduino 5 v I2c module to  ESP 3.3 supply ? however should I better to use external pull up of ESP pull up?
also I reviewed your library and very nice wrapping and managing interrupt in the Class , can you advice such library for ESP and Hal sensor

**Comment by chaeplin** [comment]
It depends on spec of each model(required voltage), some works, some not.
Some i2c breakout board has built-in pull-up resistor on it.
https://www.tindie.com/products/explorelabs/accelerometer-3-axis-mma8452q-i2c/
https://learn.sparkfun.com/tutorials/mma8452q-accelerometer-breakout-hookup-guide

PietteTech_DHT-8266 is based on PietteTech_DHT.
